version: '2.1'
services:
  db:
    image: $DB
    command: --max-connections=500 --max-allowed-packet=$PACKET --innodb-log-file-size=$INNODB_LOG_FILE_SIZE --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --ssl-ca=/etc/sslcert/ca.crt --ssl-cert=/etc/sslcert/server.crt --ssl-key=/etc/sslcert/server.key --bind-address=0.0.0.0 --performance-schema=ON $ADDITIONAL_CONF
    ports:
      - 3305:3306
    volumes:
      - $SSLCERT:/etc/sslcert
      - $ENTRYPOINT:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: testj
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_INITDB_SKIP_TZINFO: 1
