version: '2'
services:
  node1:
    image: mariadb:10.2
    environment:
      MYSQL_DATABASE: testj
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - 3106:3306
    command: --max-connections=500 --wsrep_new_cluster --wsrep_cluster_address='gcomm://node1,node2,node3' --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci  --bind-address=0.0.0.0 --wsrep-new-cluster --binlog-format=ROW --wsrep-provider=/usr/lib/galera/libgalera_smm.so --wsrep-cluster-name=my_super_cluster --wsrep-on=ON --ssl-ca=/etc/sslcert/ca.crt --ssl-cert=/etc/sslcert/server.crt --ssl-key=/etc/sslcert/server.key
    volumes:
      - $SSLCERT:/etc/sslcert
      - $ENTRYPOINT:/docker-entrypoint-initdb.d
  node2:
    image: mariadb:10.2
    depends_on:
      - node1
    environment:
      MYSQL_DATABASE: testj
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - 3107:3306
    command: --max-connections=500 --wsrep_cluster_address='gcomm://node1,node2,node3' --wsrep-node-name=node2 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci  --bind-address=0.0.0.0 --wsrep-new-cluster --binlog-format=ROW --wsrep-provider=/usr/lib/galera/libgalera_smm.so --wsrep-cluster-name=my_super_cluster  --wsrep-on=ON --ssl-ca=/etc/sslcert/ca.crt --ssl-cert=/etc/sslcert/server.crt --ssl-key=/etc/sslcert/server.key
    volumes:
      - $SSLCERT:/etc/sslcert
      - $ENTRYPOINT:/docker-entrypoint-initdb.d
  node3:
    image: mariadb:10.2
    depends_on:
      - node1
    environment:
      MYSQL_DATABASE: testj
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - 3108:3306
    command: --max-connections=500 --wsrep_cluster_address='gcomm://node1,node2,node3' --wsrep-node-name=node3 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci  --bind-address=0.0.0.0 --wsrep-new-cluster --binlog-format=ROW --wsrep-provider=/usr/lib/galera/libgalera_smm.so --wsrep-cluster-name=my_super_cluster  --wsrep-on=ON --ssl-ca=/etc/sslcert/ca.crt --ssl-cert=/etc/sslcert/server.crt --ssl-key=/etc/sslcert/server.key
    volumes:
      - $SSLCERT:/etc/sslcert
      - $ENTRYPOINT:/docker-entrypoint-initdb.d
